AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DataLakeBucketName:
    Type: String

  FernetKey:
    Type: String
    NoEcho: true

  AirflowDBUsername:
    Default: airflow
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '^[a-zA-Z_][a-zA-Z0-9_]*$'
    ConstraintDescription: >-
      Must begin with a letter or underscore and contain only letters, 
      numbers, or underscores.

  DataWarehouseUsername:
    Default: crypto_warehouse
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '^[a-zA-Z_][a-zA-Z0-9_]*$'
    ConstraintDescription: >-
      Must begin with a letter or underscore and contain only letters, 
      numbers, or underscores.
  
  AirflowDBInstanceID:
    Default: airflow-metadata-db
    Type: String
    MinLength: 1
    MaxLength: 63
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9-]*[a-zA-Z0-9]$'
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.

  AllocatedStorageAirflowDB:
    Default: 20
    Description: The size of the database (GiB)
    Type: Number
    MinValue: 20
    MaxValue: 65536
    ConstraintDescription: must be between 20 and 65536 GiB.

  DataWarehouseInstanceID:
    Default: crypto-warehouse
    Type: String
    MinLength: 1
    MaxLength: 63
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9-]*[a-zA-Z0-9]$'
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.

  AllocatedStorageDataWarehouse:
    Default: 20
    Description: The size of the database (GiB)
    Type: Number
    MinValue: 20
    MaxValue: 65536
    ConstraintDescription: must be between 20 and 65536 GiB.

  DBInstanceClass:
    Default: db.t4g.micro
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.

  EngineVersion:
    Default: 17.4
    Description: DB engine version
    Type: String
    ConstraintDescription: Must select a valid engine version.

Resources:
  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: templates/storage.yaml
      Parameters:
        DataLakeBucketName: !Ref DataLakeBucketName

  PoliciesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/policies.yaml
      Parameters:
        DataLakeBucketArn: !GetAtt StorageStack.Outputs.DataLakeBucketArn

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/database.yaml
      Parameters:
        AirflowDBUsername: !Ref AirflowDBUsername
        DataWarehouseUsername: !Ref DataWarehouseUsername
        AirflowDBInstanceID: !Ref AirflowDBInstanceID
        AllocatedStorageAirflowDB: !Ref AllocatedStorageAirflowDB
        DataWarehouseInstanceID: !Ref DataWarehouseInstanceID
        AllocatedStorageDataWarehouse: !Ref AllocatedStorageDataWarehouse
        DBInstanceClass: !Ref DBInstanceClass
        EngineVersion: !Ref EngineVersion
  
  SecretsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/secrets.yaml
      Parameters:
        AirflowDBUsername: !Ref AirflowDBUsername
        AirflowDBPassword: !Sub '{{resolve:secretsmanager:${DatabaseStack.Outputs.AirflowDBSecretArn}:SecretString:password}}'
        AirflowDBHost: !GetAtt DatabaseStack.Outputs.AirflowMetadataDBEndpoint
        FernetKey: !Ref FernetKey