AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DataLakeBucketArn:
    Type: String

  AirflowDBSecretArn:
    Type: String
  
  AirflowDBEndpoint:
    Type: String

  ClusterName:
    Default: crypto-etl-pipeline-cluster
    Type: String

  TaskDefinitionFamily:
    Default: crypto-etl-pipeline
    Type: String
  
  Cpu:
    Default: 1024 # 1 vCPU
    Type: String

  Memory:
    Default: 3072 # 3 GB
    Type: String
  
  ApplicationName:
    Default: crypto-etl-pipeline
    Type: String

  ImageURI:
    Default: ghcr.io/caiomunhoz/crypto-etl-pipeline:latest
    Type: String
  
  DataLakeBucketName:
    Type: String
  
  FernetKey:
    Type: String
    NoEcho: true
  
  LoadBalancerDNS:
    Type: String
   
  ServiceName:
    Default: crypto-etl-pipeline-service
    Type: String
  
  ServiceDesiredCount:
    Default: 1
    Type: Number

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>

  AirflowSecurityGroup:
    Type: String

  AirflowTargetGroupArn:
    Type: String

Resources:
  AirflowSQLAlchemyConnSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: airflow/config/sql-alchemy-conn
      SecretString: !Sub 'postgresql+psycopg2://{{resolve:secretsmanager:${AirflowDBSecretArn}:SecretString:username}}:{{resolve:secretsmanager:${AirflowDBSecretArn}:SecretString:password}}@${AirflowDBEndpoint}/postgres'

  AirflowFernetKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: airflow/config/fernet-key
      SecretString: !Ref FernetKey

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: 
              Service: 
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: data-lake-bucket-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:ListBucket
                Resource: !Ref DataLakeBucketArn
              - Effect: Allow
                Action:
                 - s3:PutObject
                 - s3:GetObject
                Resource: !Sub '${DataLakeBucketArn}/*'
        - PolicyName: airflow-secrets-access
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: 
                - !Ref AirflowSQLAlchemyConnSecret
                - !Ref AirflowFernetKeySecret

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: 
              Service: 
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  AirflowCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName

  AirflowTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref TaskDefinitionFamily
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: !Ref TaskRole
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: db-migration
          Image: !Ref ImageURI
          EntryPoint:
            - "bash"
            - "-c"
          Command:
            - "airflow db migrate"
          Essential: false
          Environment:
            - Name: AIRFLOW__SECRETS__BACKEND
              Value: "airflow.providers.amazon.aws.secrets.secrets_manager.SecretsManagerBackend"
            - Name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_SECRET
              Value: sql-alchemy-conn
            - Name: AIRFLOW__CORE__FERNET_KEY_SECRET
              Value: fernet-key
            - Name: AIRFLOW_VAR_BUCKET_NAME
              Value: !Ref DataLakeBucketName
            - Name: AIRFLOW__CORE__EXECUTOR
              Value: LocalExecutor

        - Name: create-admin
          Image: !Ref ImageURI
          EntryPoint:
            - "bash"
            - "-c"
          Command:
            - >
                airflow users create \
                --username admin \
                --password admin \
                --firstname Admin \
                --lastname User \
                --role Admin \
                --email admin@example.com
          Essential: false
          Environment:
            - Name: AIRFLOW__SECRETS__BACKEND
              Value: "airflow.providers.amazon.aws.secrets.secrets_manager.SecretsManagerBackend"
            - Name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_SECRET
              Value: sql-alchemy-conn
            - Name: AIRFLOW__CORE__FERNET_KEY_SECRET
              Value: fernet-key
            - Name: AIRFLOW__CORE__EXECUTOR
              Value: LocalExecutor

        - Name: api-server
          Image: !Ref ImageURI
          EntryPoint:
            - "bash"
            - "-c"
          Command:
            - "airflow api-server"
          Essential: true
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: AIRFLOW__SECRETS__BACKEND
              Value: "airflow.providers.amazon.aws.secrets.secrets_manager.SecretsManagerBackend"
            - Name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_SECRET
              Value: sql-alchemy-conn
            - Name: AIRFLOW__CORE__FERNET_KEY_SECRET
              Value: fernet-key
            - Name: AIRFLOW__CORE__EXECUTOR
              Value: LocalExecutor
            - Name: AIRFLOW__API__BASE__URL
              Value: !Sub "http://${LoadBalancerDNS}"
            - Name: AIRFLOW__LOGGING__BASE_URL
              Value: !Sub "http://${LoadBalancerDNS}"
            - Name: AIRFLOW_VAR_BUCKET_NAME
              Value: !Ref DataLakeBucketName
            - Name: AIRFLOW_VAR_COINGECKO_ENDPOINT
              Value: "https://api.coingecko.com/api/v3/simple/price"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/airflow
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: airflow-api-server

        - Name: scheduler
          Image: !Ref ImageURI
          EntryPoint:
            - "bash"
            - "-c"
          Command:
            - "airflow scheduler"
          Essential: false
          Environment:
            - Name: AIRFLOW__SECRETS__BACKEND
              Value: "airflow.providers.amazon.aws.secrets.secrets_manager.SecretsManagerBackend"
            - Name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_SECRET
              Value: sql-alchemy-conn
            - Name: AIRFLOW__CORE__FERNET_KEY_SECRET
              Value: fernet-key
            - Name: AIRFLOW__CORE__EXECUTOR
              Value: LocalExecutor

        - Name: triggerer
          Image: !Ref ImageURI
          EntryPoint:
            - "bash"
            - "-c"
          Command:
            - "airflow triggerer"
          Essential: false
          Environment:
            - Name: AIRFLOW__SECRETS__BACKEND
              Value: "airflow.providers.amazon.aws.secrets.secrets_manager.SecretsManagerBackend"
            - Name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_SECRET
              Value: sql-alchemy-conn
            - Name: AIRFLOW__CORE__FERNET_KEY_SECRET
              Value: fernet-key
            - Name: AIRFLOW__CORE__EXECUTOR
              Value: LocalExecutor

        - Name: dag-processor
          Image: !Ref ImageURI
          EntryPoint:
            - "bash"
            - "-c"
          Command:
            - "airflow dag-processor"
          Essential: false
          Environment:
            - Name: AIRFLOW__SECRETS__BACKEND
              Value: "airflow.providers.amazon.aws.secrets.secrets_manager.SecretsManagerBackend"
            - Name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_SECRET
              Value: sql-alchemy-conn
            - Name: AIRFLOW__CORE__FERNET_KEY_SECRET
              Value: fernet-key
            - Name: AIRFLOW__CORE__EXECUTOR
              Value: LocalExecutor
          
  AirflowService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref AirflowCluster
      ServiceName: !Ref ServiceName
      LaunchType: FARGATE
      DesiredCount: !Ref ServiceDesiredCount
      TaskDefinition: !Ref AirflowTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref Subnets
          SecurityGroups:
            - !Ref AirflowSecurityGroup
      LoadBalancers:
        - TargetGroupArn: !Ref AirflowTargetGroupArn
          ContainerName: api-server
          ContainerPort: 8080
