AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AirflowDBUsername:
    Type: String

  AirflowDBPassword:
    Type: String
    NoEcho: true

  AirflowDBHost:
    Type: String

  FernetKey:
    Type: String
    NoEcho: true

Resources:
  SQLAlchemyConnSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: airflow/config/sql-alchemy-conn
      SecretString: !Sub 'postgresql+psycopg2://${AirflowDBUsername}:${AirflowDBPassword}@${AirflowDBHost}/postgres'
  
  FernetKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: airflow/config/fernet-key
      SecretString: !Ref FernetKey