AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ClusterName:
    Default: airflow-cluster
    Type: String

  TaskDefinitionFamily:
    Default: 
    Type: String

Resources:
  AirflowCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref TaskDefinitionFamily
      Essential: true