AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AirflowDBInstanceID:
    Default: airflow-metadata-db
    Type: String
    MinLength: 1
    MaxLength: 63
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9-]*[a-zA-Z0-9]$'
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.
  
  AirflowDBSecretArn:
    Type: String

  AllocatedStorageAirflowDB:
    Default: 20
    Description: The size of the database (GiB)
    Type: Number
    MinValue: 20
    MaxValue: 65536
    ConstraintDescription: must be between 20 and 65536 GiB.

  DataWarehouseInstanceID:
    Default: crypto-warehouse
    Type: String
    MinLength: 1
    MaxLength: 63
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9-]*[a-zA-Z0-9]$'
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.

  DataWarehouseSecretArn:
    Type: String

  AllocatedStorageDataWarehouse:
    Default: 20
    Description: The size of the database (GiB)
    Type: Number
    MinValue: 20
    MaxValue: 65536
    ConstraintDescription: must be between 20 and 65536 GiB.

  DBInstanceClass:
    Default: db.t4g.micro
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.

  EngineVersion:
    Default: 17.4
    Description: DB engine version
    Type: String
    ConstraintDescription: Must select a valid engine version.

Resources:
  AirflowMetadataDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref AirflowDBInstanceID
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref AllocatedStorageAirflowDB
      Engine: postgres
      EngineVersion: !Ref EngineVersion
      MasterUsername: !Sub '{{resolve:secretsmanager:${AirflowDBSecretArn}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${AirflowDBSecretArn}:SecretString:password}}'

  DataWarehouse:
    Type: AWS::RDS::DBInstance
    Properties:
        DBInstanceIdentifier: !Ref DataWarehouseInstanceID
        DBInstanceClass: !Ref DBInstanceClass
        AllocatedStorage: !Ref AllocatedStorageDataWarehouse
        Engine: postgres
        EngineVersion: !Ref EngineVersion
        MasterUsername: !Sub '{{resolve:secretsmanager:${DataWarehouseSecretArn}:SecretString:username}}'
        MasterUserPassword: !Sub '{{resolve:secretsmanager:${DataWarehouseSecretArn}:SecretString:password}}'