AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DataLakeBucketName:
    Type: String

  AirflowDBUsername:
    Default: airflow
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '^[a-zA-Z_][a-zA-Z0-9_]*$'
    ConstraintDescription: >-
      Must begin with a letter or underscore and contain only letters, 
      numbers, or underscores.

  DataWarehouseUsername:
    Default: crypto_warehouse
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '^[a-zA-Z_][a-zA-Z0-9_]*$'
    ConstraintDescription: >-
      Must begin with a letter or underscore and contain only letters, 
      numbers, or underscores.
  
  AirflowDBInstanceID:
    Default: airflow-metadata-db
    Type: String
    MinLength: 1
    MaxLength: 63
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9-]*[a-zA-Z0-9]$'
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.

  AllocatedStorageAirflowDB:
    Default: 20
    Description: The size of the database (GiB)
    Type: Number
    MinValue: 20
    MaxValue: 65536
    ConstraintDescription: must be between 20 and 65536 GiB.

  DataWarehouseInstanceID:
    Default: crypto-warehouse
    Type: String
    MinLength: 1
    MaxLength: 63
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9-]*[a-zA-Z0-9]$'
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.

  AllocatedStorageDataWarehouse:
    Default: 20
    Description: The size of the database (GiB)
    Type: Number
    MinValue: 20
    MaxValue: 65536
    ConstraintDescription: must be between 20 and 65536 GiB.

  DBInstanceClass:
    Default: db.t4g.micro
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.

  EngineVersion:
    Default: 17.4
    Description: DB engine version
    Type: String
    ConstraintDescription: Must select a valid engine version.

  VpcId:
    Type: AWS::EC2::VPC::Id

  PublicSubnets:
    Type: List<AWS::EC2:Subnet::Id>

  SecurityGroupDescription:
    Default: Security group for Airflow resources (UI + metadata db access)
    Type: String

  AirflowLoadBalancerName:
    Default: airflow-alb
    Type: String
  
  AirflowTargetGroupName:
    Default: airflow-tg
    Type: String
  
  ECSClusterName:
    Default: crypto-etl-pipeline-cluster
    Type: String

  ECSTaskDefinitionFamily:
    Default: crypto-etl-pipeline
    Type: String
  
  ECSCpu:
    Default: 1024 # 1 vCPU
    Type: String

  ECSMemory:
    Default: 3072 # 3 GB
    Type: String
  
  ECSImageURI:
    Default: ghcr.io/caiomunhoz/crypto-etl-pipeline:latest
    Type: String
  
  FernetKey:
    Type: String
    NoEcho: true

Resources:
  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: templates/storage.yaml
      Parameters:
        DataLakeBucketName: !Ref DataLakeBucketName

  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/iam_roles.yaml
      Parameters:
        DataLakeBucketArn: !GetAtt StorageStack.Outputs.DataLakeBucketArn

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/database.yaml
      Parameters:
        AirflowDBUsername: !Ref AirflowDBUsername
        DataWarehouseUsername: !Ref DataWarehouseUsername
        AirflowDBInstanceID: !Ref AirflowDBInstanceID
        DataWarehouseInstanceID: !Ref DataWarehouseInstanceID
        DBInstanceClass: !Ref DBInstanceClass
        EngineVersion: !Ref EngineVersion

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/network.yaml
      Parameters:
        VpcId: !Ref VpcId
        PublicSubnets: !Ref PublicSubnets
        SecurityGroupDescription: !Ref SecurityGroupDescription
        AirflowLoadBalancerName: !Ref AirflowLoadBalancerName
        AirflowTargetGroupName: !Ref AirflowTargetGroupName

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/compute.yaml
      Parameters:
        AirflowDBSecretArn: !GetAtt DatabaseStack.Outputs.AirflowDBSecretArn
        AirflowDBEndpoint: !GetAtt DatabaseStack.Outputs.AirflowMetadataDBEndpoint
        ClusterName: !Ref ECSClusterName
        TaskDefinitionFamily: !Ref ECSTaskDefinitionFamily
        Cpu: !Ref ECSCpu
        Memory: !Ref ECSMemory
        ExecutionRoleArn: !GetAtt IAMRolesStack.Outputs.ECSTaskExecutionRoleArn
        TaskRoleArn: !GetAtt IAMRolesStack.Outputs.ECSTaskRoleArn
        ImageURI: !Ref ECSImageURI
        DataLakeBucketName: !Ref DataLakeBucketName
        FernetKey: !Ref FernetKey
        LoadBalancerDNS: !GetAtt NetworkStack.Outputs.LoadBalancerDNS