AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DataLakeBucketName:
    Type: String

  AirflowDBUsername:
    Type: String

  DataWarehouseUsername:
    Type: String
  
  DBInstanceClass:
    Type: String

  EngineVersion:
    Type: String

Resources:
  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties: ./storage.yaml'
    Parameters:
      DataLakeBucketName: !Ref DataLakeBucketName

  SecretsStack:
    Type: AWS::CloudFormation::Stack
    Properties: ./secrets.yaml'
    Parameters:
      AirflowDBUsername: !Ref AirflowDBUsername
      DataWarehouseUsername: !Ref DataWarehouseUsername

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties: ./database.yaml'
    Parameters:
      AirflowDBInstanceID: !Ref AirflowDBInstanceID
      AirflowDBSecretArn: !ImportValue AirflowDBSecret
      DataWarehouseInstanceID: !Ref DataWarehouseInstanceID
      DataWarehouseSecretArn: !ImportValue DataWarehouseSecret
      DBInstanceClass: !Ref DBInstanceClass
      EngineVersion: !Ref EngineVersion

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties: ./network.yaml'

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties: ./compute.yaml'