AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AirflowDBUsername:
    Default: airflow
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9-]*[a-zA-Z0-9]$'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.

  DataWarehouseUsername:
    Default: cryptowarehouse
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9-]*[a-zA-Z0-9]$'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.

Resources:
  AirflowDBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: airflow-metadata-db-secret
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${AirflowDBUsername}"}'
        GenerateStringKey: password
        PasswordLength: 30
  
  DataWarehouseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: data-warehouse-secret
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DataWarehouseUsername}"}'
        GenerateStringKey: password
        PasswordLength: 30

Outputs:
  AirflowDBSecretArn:
    Value: !Ref AirflowDBSecret
    Export:
      Name: AirflowDBSecret

  DataWarehouseSecretArn:
    Value: !Ref DataWarehouseSecret
    Export:
      Name: DataWarehouseSecret