AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AirflowDBSecretArn:
    Type: String
  
  AirflowDBEndpoint:
    Type: String

  ClusterName:
    Default: crypto-etl-pipeline-cluster
    Type: String

  TaskDefinitionFamily:
    Default: crypto-etl-pipeline
    Type: String
  
  Cpu:
    Default: 1024 # 1 vCPU
    Type: String

  Memory:
    Default: 3072 # 3 GB
    Type: String
  
  ApplicationName:
    Type: String
  
  ExecutionRoleArn:
    Type: String
  
  TaskRoleArn:
    Type: String
  
  ImageURI:
    Default: ghcr.io/caiomunhoz/crypto-etl-pipeline:latest
    Type: String
  
  DataLakeBucketName:
    Type: String
  
  FernetKey:
    Type: String
    NoEcho: true
  
  LoadBalancerDNS:
    Type: String

Resources:
  AirflowSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: airflow-secrets
      SecretString: !Sub >
        {
          "connection": "postgresql+psycopg2://{{resolve:secretsmanager:${AirflowDBSecretArn}:SecretString:username}}:
          {{resolve:secretsmanager:${AirflowDBSecretArn}:SecretString:password}}@
          ${AirflowDBEndpoint}/postgres",
          "fernet_key": ${FernetKey}
        }

  AirflowCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref TaskDefinitionFamily
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      ContainerDefinitions:
        - Name: !Ref ApplicationName
          Cpu: !Ref Cpu
          Memory: !Ref Memory
          Image: !Ref ImageURI
          PortMappings: 
            - ContainerPort: 8080
              HostPort: 8080
              AppProtocol: http
          Environment:
            - Name: AIRFLOW__CORE__EXECUTOR
              Value: LocalExecutor
            - Name: AIRFLOW__LOGGING__HOSTNAME_CALLABLE
              Value: socket.gethostname
            - Name: AIRFLOW__API__BASE__URL
              Value: !Ref LoadBalancerDNS
            - Name: AIRFLOW__LOGGING__BASE_URL
              Value: !Ref LoadBalancerDNS
            - Name: AIRFLOW_VAR_BUCKET_NAME
              Value: !Ref DataLakeBucketName
            - Name: AIRFLOW_VAR_COINGECKO_ENDPOINT
              Value: https://api.coingecko.com/api/v3/simple/price
          Secrets:
            - Name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              ValueFrom: !Sub '${AirflowSecrets}:connection::'
            - Name: AIRFLOW__CORE__FERNET_KEY
              ValueFrom: !Sub '${AirflowSecrets}:fernet_key::'
