AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DataLakeBucketArn:
    Type: String

Resources:
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: 
              Service: 
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: data-lake-bucket-min-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:ListBucket
                Resource: !Ref DataLakeBucketArn
              - Effect: Allow
                Action:
                 - s3:PutObject
                 - s3:GetObject
                Resource: !Sub ${DataLakeBucketArn}/*

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: 
              Service: 
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

Outputs:
  ECSTaskRoleArn:
    Value: !Ref ECSTaskRole
    Export:
      Name: ECSTaskRoleArn
  
  ECSTaskExecutionRoleArn:
    Value: !Ref ECSTaskExecutionRole
    Export:
      Name: ECSTaskExecutionRoleArn