AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AirflowDBUsername:
    Default: airflow
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '^[a-zA-Z_][a-zA-Z0-9_]*$'
    ConstraintDescription: >- 
      Must begin with a letter or underscore and contain only letters, 
      numbers, or underscores.

  DataWarehouseUsername:
    Default: crypto_warehouse
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '^[a-zA-Z_][a-zA-Z0-9_]*$'
    ConstraintDescription: >- 
      Must begin with a letter or underscore and contain only letters, 
      numbers, or underscores.

Resources:
  AirflowDBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: airflow-metadata-db-secret
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${AirflowDBUsername}"}'
        GenerateStringKey: password
        PasswordLength: 30
        ExcludePunctuation: true
        RequireEachIncludedType: true

  DataWarehouseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: data-warehouse-secret
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DataWarehouseUsername}"}'
        GenerateStringKey: password
        PasswordLength: 30
        ExcludePunctuation: true
        RequireEachIncludedType: true

Outputs:
  AirflowDBSecretArn:
    Value: !Ref AirflowDBSecret
    Export:
      Name: AirflowDBSecretArn

  DataWarehouseSecretArn:
    Value: !Ref DataWarehouseSecret
    Export:
      Name: DataWarehouseSecretArn